IDEA-352355 support MutableSharedFlow and MutableStateFlow
JetBrains/debugger-agent pull request #2
Opened 2024-08-14 09:01 UTC by AlexVanGogen

Corresponding change in coroutines: https://github.com/JetBrains/intellij-deps-kotlinx.coroutines/pull/4

2024-08-14 09:47 UTC, cypok commented
LGTM

2024-08-14 10:09 UTC, gorrus requested changes

2024-08-14 10:09 UTC, gorrus commented on src/main/java/com/intellij/rt/debugger/agent/CaptureAgent.java
> +  private static class SharedFlowTransformer implements ClassFileTransformer {
please move SharedFlowTransformer class outside of the file

2024-08-14 14:57 UTC, AlexVanGogen commented on src/main/java/com/intellij/rt/debugger/agent/CaptureAgent.java
> +  private static class SharedFlowTransformer implements ClassFileTransformer {
Done

2024-08-15 08:51 UTC, gorrus requested changes

2024-08-15 08:51 UTC, gorrus commented on src/main/java/com/intellij/rt/debugger/agent/SharedFlowTransformer.java
> +            protected ClassLoader getClassLoader() {
is it still needed?

2024-08-15 10:28 UTC, gorrus commented on src/main/java/com/intellij/rt/debugger/agent/SharedFlowTransformer.java
> +        ClassWriter writer = new ClassWriter(reader, ClassWriter.COMPUTE_FRAMES) {
is ClassWriter.COMPUTE_FRAMES still needed?

2024-08-15 10:30 UTC, gorrus commented on src/main/java/com/intellij/rt/debugger/agent/SharedFlowTransformer.java
> +        return writer.toByteArray();
maybe call storeClassForDebug for debug purposes

2024-08-16 15:40 UTC, AlexVanGogen commented on src/main/java/com/intellij/rt/debugger/agent/SharedFlowTransformer.java
> +            protected ClassLoader getClassLoader() {
No, it seems

2024-08-16 15:41 UTC, AlexVanGogen commented on src/main/java/com/intellij/rt/debugger/agent/SharedFlowTransformer.java
> +        ClassWriter writer = new ClassWriter(reader, ClassWriter.COMPUTE_FRAMES) {
Yes, but I tried to handle it manually, and the result seems to work

2024-08-19 09:58 UTC, gorrus approved these changes

2024-08-20 10:18 UTC, merged