IDEA-352355 enhance support for async stack traces in flows
JetBrains/debugger-agent pull request #3
Opened 2024-09-04 08:28 UTC by AlexVanGogen

* simplify instrumentation by making a single insertion point source instead of having one in every class
* handle a double-wrapping case which leads to errors; allow agent to choose how to handle it
* support more commonly used operators (such as `scan`, `buffer`, `debounce` with dynamic timeout)

Related PR in coroutines fork: https://github.com/JetBrains/intellij-deps-kotlinx.coroutines/pull/5

2024-09-04 09:39 UTC, gorrus requested changes

2024-09-04 09:39 UTC, gorrus commented on src/main/java/com/intellij/rt/debugger/agent/SharedFlowTransformer.java
> +                prefix = "Strict";
strictly speaking it is a postfix, but to me looks better to have one method with a parameter

2024-09-04 09:59 UTC, AlexVanGogen commented on src/main/java/com/intellij/rt/debugger/agent/SharedFlowTransformer.java
> +                prefix = "Strict";
🤦 postfix, right. Why does one method look better to you, though? I don't see big difference, though to me it seems a little bit simpler to reason about instrumentation saying "**this** method will call **that** method" instead of "**this** method will call that method with **that** parameter".

Parameter also brings additional if on a hot path. It will be JIT'ed instantly, but still...

2024-09-05 09:11 UTC, gorrus commented on src/main/java/com/intellij/rt/debugger/agent/SharedFlowTransformer.java
> +                prefix = "Strict";
for me it is having extra two methods in the library for the debugging purposes only instead of one

2024-09-05 09:21 UTC, cypok commented on src/main/java/com/intellij/rt/debugger/agent/SharedFlowTransformer.java
> +                prefix = "Strict";
Unfortunately, I won't help. Compile time method dispatching is better than a runtime parameter. However, the reasoning about a single method is also true. :)

2024-09-05 09:21 UTC, cypok approved these changes

2024-09-09 09:06 UTC, AlexVanGogen commented on src/main/java/com/intellij/rt/debugger/agent/SharedFlowTransformer.java
> +                prefix = "Strict";
Dilemma solved, but in a somewhat brutal way

2024-09-09 09:13 UTC, gorrus approved these changes

2024-09-10 12:58 UTC, merged